name: CI

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main

env:
  REGISTRY: dataswift/base

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v1

      - name: Container - Login
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_DATASWIFT_USER }}
          password: ${{ secrets.DOCKERHUB_DATASWIFT_PASS }}
      
      - name: Container - Login
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: ${{ env.REGISTRY }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}:latest
