name: CI

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Container - Build
        run: docker build -t dataswift/base . 
