name: CI

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v1

      - name: Container - Login GitHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: dataswiftbotie
          password: ${{ secrets.BOT_GITHUB_TOKEN }}

      - name: Container - Build & Push
        uses: docker/build-push-action@v2
        with:
          push: false
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=ghcr.io/dataswift/base:latest
