name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

env:
  REGISTRY: dataswift/base

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v1

      - name: Container - Login DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_DATASWIFT_USER }}
          password: ${{ secrets.DOCKERHUB_DATASWIFT_PASS }}

      - name: Container - Login GitHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: dataswiftbotie
          password: ${{ secrets.BOT_GITHUB_TOKEN }}          

      - name: Container - Meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            datasiwft/base
            ghcr.io/datasiwft/base
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha      

      - name: Container - Build & Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=ghcr.io/datasiwft/base:latest
