name: Trivy

on:
  workflow_dispatch:
  schedule:
    - cron: "30 3 * * *"

jobs:
  trivy-scan:
    name: Trivy Scan
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Container - Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/dataswift/base:latest
          format: "template"
          exit-code: 1
          ignore-unfixed: true
          template: "@/contrib/sarif.tpl"
          output: "trivy-results.sarif"
          severity: "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"

      - name: Container - Scan - Upload results
        uses: github/codeql-action/upload-sarif@v1
        if: ${{ failure() }}
        with:
          sarif_file: "trivy-results.sarif"

      - name: Jira Login
        if: ${{ failure() }}
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Jira Issue
        if: ${{ failure() }}
        uses: atlassian/gajira-create@master
        with:
          project: ${{ secrets.JIRA_TRIVY_PROJECT }}
          issuetype: ${{ secrets.JIRA_TRIVY_ISSUE_TYPE }}
          summary: Trivy Security Alert - ${{ github.repository }}
